# Generated by Django 4.2.4 on 2023-08-31 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_location_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Select Category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.subcategory', verbose_name='SubCategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SubCategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SubCategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SubCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Select Category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category', verbose_name='Category'),
        ),
    ]
